kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /home/cthain/github.com/cthain/overwatch-demo/extensions
    containerPath: /consul-extensions
    readOnly: true
